name = "RiemannianSSMs"
uuid = "2a6b6a9a-ad85-4cf8-8cda-b21ac2480253"
authors = ["Tim Hargreaves"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Distributions = "0.25.120"
FiniteDiff = "2.28.1"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
StableRNGs = "1.0.3"
StaticArrays = "1.9.14"
TestItemRunner = "1.1.0"
TestItems = "1.0.0"
julia = "1.6.7"

[extras]
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[targets]
test = ["FiniteDiff", "StableRNGs", "Test", "TestItemRunner", "TestItems"]
